spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mybatis_plus
      username: root
      password: 1qaz,2wsx
      driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: 192.168.52.11
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.52.11
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池中的最大空闲连接
        max-idle: 300
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 1000



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
gis:
  tencent:
    url: https://apis.map.qq.com/ws/geocoder/v1
    key: O3QBZ-6KV66-KC3SE-ESJIR-GELXJ-RUBOK
    def_addr: 哈尔滨